apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: sample-app
  annotations:
    selfheal.io/correlation-id: "67f8553f-ada9-4120-b4dd-bdbaf975e49c"
    selfheal.io/last-action: "scale_deployment"
    selfheal.io/triggered-by: "argo_workflow"
spec:
  replicas: 5
