apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: sample-app
  annotations:
    selfheal.io/correlation-id: "405d82fd-5a84-460c-b014-42231d716a72"
    selfheal.io/last-action: "scale_deployment"
    selfheal.io/triggered-by: "argo_workflow"
spec:
  replicas: 5
